In [4]:
# Unknown Dimesion
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [5]:
arr = np.array([0,1,2,3,4,5,6,7])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [6]:
arr = np.array([0,1,2,3,4,5,6,7])
newarr = arr.reshape(2,-1,-1)


ValueError: can only specify one unknown dimension

In [9]:
arr = np.array([0,1,2,3,4,5,6,7])
newarr = arr.reshape(2,-1,2)
print(newarr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [10]:
arr = np.array([0,1,2,3,4,5,6,7])
newarr = arr.reshape(-1,2,2)
print(newarr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)
arr = np.array([0,1,2,3,4,5,6,7])
newarr = arr.reshape(-1,2,2)
flatten_array = newarr.reshape(-1)
print(flatten_array)

[1 2 3 4 5 6]
[0 1 2 3 4 5 6 7]


In [14]:
arr = np.array([0,1,2,3,4,5,6,7])

for item in arr:
    print(item)

0
1
2
3
4
5
6
7


In [17]:
arr = np.array([[0,1,2,3],[4,5,6,7]])
for item in arr:
    print(item)
    
for x_item in arr:
    for y_item in x_item:
        print(y_item)



[0 1 2 3]
[4 5 6 7]
0
1
2
3
4
5
6
7


In [19]:
arr = np.array([[[0,1],[2,3],[4,5],[6,7]]])

for item in np.nditer(arr):
    print(item)

0
1
2
3
4
5
6
7


In [29]:
arr = np.array([[[0,1],[2,3],[4,5],[6,7]]])
print('convert to string')
for item in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(item)
print('convert to float')
for item in np.nditer(arr, flags=['buffered'], op_dtypes=['f'],casting='unsafe'):
    print(item)

convert to string
b'0'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
convert to float
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0


In [33]:
arr = np.array([[0,1,2,3],[4,5,6,7], [8,9,10,11],[12,13,14,15]])
print("Step of 2 in second dimension")
for item in np.nditer(arr[:, ::2]):
    print(item)
print("Step of 2 in first dimension")
for item in np.nditer(arr[::2, :]):
    print(item)


Step of 2 in second dimension
0
2
4
6
8
10
12
14
Step of 2 in first dimension
0
1
2
3
8
9
10
11


In [39]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr = np.concatenate((arr_1, arr_2))
print(arr)

arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr_1, arr_2))
print(arr)
# concatenate with axis = 1
arr = np.concatenate((arr_1, arr_2), axis=1)
print(arr)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [45]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr = np.stack((arr_1, arr_2), axis=1)
print(arr)

arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6],[7,8]])
arr = np.stack((arr_1, arr_2), axis=1)
print("axis = 1")
print(arr)
print("axis = 2")
arr = np.stack((arr_1, arr_2), axis=2)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
axis = 1
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
axis = 2
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [51]:

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
print("Row Stacking")
# Stacking along rows
arr = np.hstack((arr_1,arr_2))
print(arr)
print("Column Stacking")
# Stacking along columns
arr = np.vstack((arr_1,arr_2))
print(arr)
print("Height Stacking")
# Stacking along height/depth
arr = np.dstack((arr_1,arr_2))
print(arr)

Row Stacking
[1 2 3 4 5 6]
Column Stacking
[[1 2 3]
 [4 5 6]]
Height Stacking
[[[1 4]
  [2 5]
  [3 6]]]


In [54]:
# Searching arrays
arr = np.array([0,1,2,3,4,5,6,7])
item = np.where(arr == 2)
print(item)

items = np.where(arr%2==0)
print(items)

items = np.where(arr >=5)
print(items)


(array([2], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)
(array([5, 6, 7], dtype=int64),)


In [59]:
arr = np.array([0,1,2,3,4,5,6,7])

index = np.searchsorted(arr,5)
print(index)

arr = np.array([15,3,4,1,9,10,6,5])
index = np.searchsorted(arr,5)
print(index)
index = np.searchsorted(arr,5, side='right')
print(index)



5
4
4
