Numpy
------

In [1]:
my_list = [1, 'a', True]
print(my_list)
print(type(my_list))

[1, 'a', True]
<class 'list'>


In [1]:
import numpy

In [3]:
array_1 = numpy.array([1,2,3])
print(array_1)
print(type(array_1))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
array_2 = numpy.array((1,2,3))
print(array_2)
print(type(array_2))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

array = np.array([1,2,3,4,5,6])
print(array)
print(type(array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [15]:
def print_array_n_dimension(array):
    print("values", array)
    print("type is", type(array))
    print("Dimension is ", array.ndim)

In [16]:
a = np.array(12)
print_array_n_dimension(a)
b = np.array([1,2,3])
print_array_n_dimension(b)
c = np.array([[1,2,3], [4,5,6]])
print_array_n_dimension(c)
d = np.array([[[1,2,3], [4,5,6]], [[-1,-2,-3], [-4,-5,-6]]])
print_array_n_dimension(d)


values 12
type is <class 'numpy.ndarray'>
Dimension is  0
values [1 2 3]
type is <class 'numpy.ndarray'>
Dimension is  1
values [[1 2 3]
 [4 5 6]]
type is <class 'numpy.ndarray'>
Dimension is  2
values [[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
type is <class 'numpy.ndarray'>
Dimension is  3


In [35]:
# zero dimension
print("a=", a)
# one dimension
print("b[0] =", b[0])
# two dimension
print("c[0] =", c[0])
print("c[0,1] =", c[0,1])
print("c[1] =",c[1])
print("c[1,2] =", c[1,2])
# three dimension
print("d[0] =", d[0])
print("d[0,1] =", d[0,1])
print("d[0,1,2] =", d[0,1,2])


12
b[0] = 1
c[0] = [1 2 3]
c[0,1] = 2
c[1] = [4 5 6]
c[1,2] = 6
d[0] = [[1 2 3]
 [4 5 6]]
d[0,1] = [4 5 6]
d[0,1,2] = 6


In [38]:
my_list = [1,2,3,4]
print("my_list[0] =", my_list[0])
print("my_list[3] =", my_list[3])
print("my_list[-1] = ", my_list[-1])



my_list[0] = 1
my_list[3] = 4
my_list[-1] =  4


In [40]:
# negative indexing
print(c)
print("c[-1,0] = ", c[-1,0])

[[1 2 3]
 [4 5 6]]
c[-1,0] =  4


In [45]:
my_list = [1,2,3,4,5,6,7,8,9,10]
print(my_list[0:3])
print(my_list[0:6:2])
print(my_list[4:])


[1, 2, 3]
[1, 3, 5]
[5, 6, 7, 8, 9, 10]


In [46]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0:3])
print(arr[0:6:2])
print(arr[4:])


[1 2 3]
[1 3 5]
[ 5  6  7  8  9 10]


In [51]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[-1, 0:2])
print(arr[0:2, 1:4])

[6 7]
[[2 3 4]
 [7 8 9]]


In [54]:
print(arr)
print(arr.dtype)
arr = np.array(['dell', 'hp', 'lenovo'])
print(arr)
print(arr.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
int32
['dell' 'hp' 'lenovo']
<U6


In [55]:
arr = np.array([0,1], dtype='S')
print(arr)
print(arr.dtype)

[b'0' b'1']
|S1


In [63]:
arr = np.array([2.5, 3.5, 4.0])
print(arr.dtype)
new_arr = arr.astype(int)
print(new_arr)
print(new_arr.dtype)
jyothi_arr = arr.astype(str)
print(jyothi_arr)
print(jyothi_arr.dtype)

float64
[2 3 4]
int32
['2.5' '3.5' '4.0']
<U32


In [79]:
arr = np.array([1,2,3,4,5,6,7])
copy_arr = arr.copy()
arr[0] = 0
print(arr)
print(copy_arr)
copy_arr[-1] = 8
print(arr)
print(copy_arr)
print("base is", copy_arr.base)

[0 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[0 2 3 4 5 6 7]
[1 2 3 4 5 6 8]
base is None


In [78]:
arr = np.array([1,2,3,4,5,6,7])
view_arr = arr.view()
print(arr)
print(view_arr)
arr[0] = 0
print(arr)
print(view_arr)
view_arr[-1] = 8
print(arr)
print(view_arr)
print("base is ", view_arr.base)


[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[0 2 3 4 5 6 7]
[0 2 3 4 5 6 7]
[0 2 3 4 5 6 8]
[0 2 3 4 5 6 8]
base is  [0 2 3 4 5 6 8]


In [88]:
arr = np.array([1,2,3,4,5,6,7])
print(f"shape of {arr} is {arr.shape}")

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f"shape of {arr} is {arr.shape}")

arr = np.array([1,2,3], ndmin=3)
print(f"shape of {arr} is {arr.shape}")

arr = np.array([1], ndmin=10)
print(f"shape of {arr} is {arr.shape}")

shape of [1 2 3 4 5 6 7] is (7,)
shape of [[1 2 3 4]
 [5 6 7 8]] is (2, 4)
shape of [[[1 2 3]]] is (1, 1, 3)
shape of [[[[[[[[[[1]]]]]]]]]] is (1, 1, 1, 1, 1, 1, 1, 1, 1, 1)


In [90]:
# Reshape from 1-D to 2-D

arr = np.array([0,1,2,3,4,5,6,7,8])
new_arr = arr.reshape(3,3)
print(new_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [92]:
# Reshape from 1-D to 3-D
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
new_arr = arr.reshape(2,3,2)
print(new_arr)
print(new_arr.base)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
