In [2]:
import numpy as np

def my_add(x,y):
    return x+y

def my_sub(x,y):
    return x-y

my_add = np.frompyfunc(my_add,2,1)
my_sub = np.frompyfunc(my_sub,2,1)

print("Result of add")
print(my_add([1,2,3,4,5], [6,7,8,9,10]))
print("Result of sub")
print(my_sub([1,2,3,4,5], [6,7,8,9,10]))


Result of add
[7 9 11 13 15]
Result of sub
[-5 -5 -5 -5 -5]


In [4]:
print(type(np.add))
print(type(my_add))


<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


In [5]:
arr1 = np.array([10,20,30])
arr2 = np.array([2,4,6])

print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.power(arr1,arr2))
print(np.mod(arr1,arr2))

[12 24 36]
[ 8 16 24]
[ 20  80 180]
[5. 5. 5.]
[      100    160000 729000000]
[0 0 0]


In [11]:
print(np.trunc([-33.3333333333333, 33.3333333333333]))
print(np.fix([-33.3333333333333, 33.3333333333333]))
print(np.floor([-33.3333333333333, 33.3333333333333]))
print(np.ceil([-33.3333333333333, 33.3333333333333]))

print(np.round(33.3333333333333, 2))


[-33.  33.]
[-33.  33.]
[-34.  33.]
[-33.  34.]
33.33


In [16]:
# log at base2
arr = np.arange(1,10)
print(np.log2(arr)) # base 2
print(np.log10(arr)) # base 10
print(np.log(arr)) # base e
from math import log
nplog = np.frompyfunc(log,2,1)
print(nplog(100,15))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


In [20]:
print(np.lcm(4,6))
arr = np.array([3,6,9])
print(np.lcm.reduce(arr))
arr = np.arange(1,20)
print(np.lcm.reduce(arr))

12
18
232792560


In [24]:
print(np.gcd(6,9))
arr = np.array([3,6,9])
print(np.gcd.reduce(arr))
arr = np.arange(2,20)
print(np.gcd.reduce(arr))

3
3
1


In [26]:
print(np.sin(np.pi/2))

arr = np.array([0,30,45,90,180,270,360])
# convert degree to radins
radians = np.deg2rad(arr)
print(radians)


1.0
[0.         0.52359878 0.78539816 1.57079633 3.14159265 4.71238898
 6.28318531]


In [32]:
arr = np.array([1,2,3,2,3,4,5,4,6,7,5,8])
uniq_arr = np.unique(arr)
print(uniq_arr)

arr1 = np.array([10,20,30,40,50])
arr2 = np.array([40,50,60,70,80])

print(np.union1d(arr1,arr2))
print(np.intersect1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))
print(np.setxor1d(arr1,arr2))


[1 2 3 4 5 6 7 8]
[10 20 30 40 50 60 70 80]
[40 50]
[10 20 30]
[10 20 30 60 70 80]
