In [2]:
import numpy as np

arr = np.array([3,4,5,6])

index = np.searchsorted(arr, 4)
print(index)

index = np.searchsorted(arr, 4, side='right')
print(index)

1
2


In [4]:
# not a right way
arr = np.array([4,1,2,0])
index = np.searchsorted(arr,1)
print(index)
index = np.searchsorted(arr,1, side='right')
print(index)

0
2


In [6]:
arr = np.array([3,5,7,9])
index = np.searchsorted(arr, [2,3,10])
print(index)

index = np.searchsorted(arr, [2,3,10], side='right')
print(index)

[0 0 4]
[0 1 4]


In [8]:
# sorting arrays
arr = np.array([4,1,2,0])
print(np.sort(arr))

arr = np.array([[3,2,5], [6,0,4]])
print(np.sort(arr))

[0 1 2 4]
[[2 3 5]
 [0 4 6]]


In [9]:
# Find all the items in the array which are odd

arr = np.array([1,2,3,4,5,6,7,8,9])

#filter array

filter_arr = []
for element in arr:
    if element %2 == 0:
        filter_arr.append(False)
    else:
        filter_arr.append(True)

new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[True, False, True, False, True, False, True, False, True]
[1 3 5 7 9]


In [10]:
# Creating Filter directly from array
arr = np.array([1,2,3,4,5,6,7,8,9])
filter_arr = arr%2==1

new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[ True False  True False  True False  True False  True]
[1 3 5 7 9]


In [18]:
# Create a Filter to filter out prime numbers between 10 to 100

numbers = [*range(10,1001)]
#print(numbers)
arr = np.array(numbers)
def is_prime(number):
    for index in range(2,number//2+1):
        if number % index == 0:
            return False
    return True
filter_arr = []
for element in arr:
    if is_prime(element):
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(arr[filter_arr])

[ 11  13  17  19  23  29  31  37  41  43  47  53  59  61  67  71  73  79
  83  89  97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173
 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271
 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383
 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491
 499 503 509 521 523 541 547 557 563 569 571 577 587 593 599 601 607 613
 617 619 631 641 643 647 653 659 661 673 677 683 691 701 709 719 727 733
 739 743 751 757 761 769 773 787 797 809 811 821 823 827 829 839 853 857
 859 863 877 881 883 887 907 911 919 929 937 941 947 953 967 971 977 983
 991 997]


In [22]:
# array from 10 to 1000
arr = np.arange(10, 10**3)
is_prime_v = np.vectorize(is_prime)
print(arr[is_prime_v(arr)])

[ 11  13  17  19  23  29  31  37  41  43  47  53  59  61  67  71  73  79
  83  89  97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173
 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271
 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383
 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491
 499 503 509 521 523 541 547 557 563 569 571 577 587 593 599 601 607 613
 617 619 631 641 643 647 653 659 661 673 677 683 691 701 709 719 727 733
 739 743 751 757 761 769 773 787 797 809 811 821 823 827 829 839 853 857
 859 863 877 881 883 887 907 911 919 929 937 941 947 953 967 971 977 983
 991 997]


In [32]:
from numpy import random

# random number between 0 to 1000
print(random.randint(1000))

# random float => 0 to 1
print(random.rand())

# random array
# 1-D
print(random.randint(1000, size=(10)))
# 2-D
print(random.randint(1000, size=(3,5)))

array = [856, 380, 238, 272, 986, 489, 726, 964, 918, 218]
print(random.choice(array))
print(random.choice(array, size=(3,3)))


476
0.5150782699684876
[396 907 529 246 810 321  55 809 106 511]
[[401 385 455  71  56]
 [489 808  59 169  10]
 [300 760 404 478 889]]
856
[[238 380 964]
 [726 986 964]
 [964 856 918]]


In [35]:
values = random.choice([0,1,2,3,4], p=[0.1,0.3,0.2,0.2,0.2], size=(50))
print(values)

dice_rolls = random.choice([1,2,3,4,5,6], p=[1/6,1/6,1/6,1/6,1/6,1/6], size=(100))
print(dice_rolls)

[1 1 1 1 3 1 4 4 1 2 1 3 1 1 1 0 2 1 1 1 3 2 4 1 3 1 4 0 0 0 4 4 0 3 0 4 1
 1 1 4 4 2 2 4 4 4 4 1 3 3]
[5 5 6 1 4 5 2 1 1 3 5 2 6 6 4 3 2 2 3 4 6 2 4 1 5 2 2 1 6 4 1 3 5 2 3 4 4
 1 4 5 3 3 5 4 6 3 3 3 5 6 6 1 3 4 5 6 2 5 6 4 4 1 3 6 2 4 2 2 2 4 1 1 6 3
 1 3 3 1 2 4 1 1 3 5 2 6 5 2 4 2 5 4 4 2 2 6 1 2 3 4]


In [36]:
values = random.choice([0,1,2,3,4], p=[0.1,0.3,0.2,0.2,0.2], size=(4,5))
print(values)

[[1 1 4 2 2]
 [1 4 1 3 1]
 [1 1 2 1 2]
 [3 3 2 4 2]]


In [47]:
arr = np.array(['2','3','4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'])

random.shuffle(arr)
print(arr)
# shuffle makes changes to the original array

arr = np.array(['2','3','4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'])
print(random.permutation(arr))
print(arr)
# permutation returns the rearranged array and orginal array will be unchanged

['7' '2' '6' 'J' '4' '3' '8' '10' 'K' '5' 'Q' '9' 'A']
['3' 'A' '6' '7' 'Q' '5' 'K' '9' '10' '8' '2' '4' 'J']
['2' '3' '4' '5' '6' '7' '8' '9' '10' 'J' 'Q' 'K' 'A']


In [49]:

x = [1,3,5,7]
y = [2,4,6,8]
# Traditional python
z = []
for i, j in zip(x,y):
    z.append(i+j)
print(z)

#ufunc
z = np.add(x,y)
print(z)

[3, 7, 11, 15]
[ 3  7 11 15]
