In [3]:
#import sys
#!conda install --yes --prefix {sys.prefix} numpy

* To create a numpy array, the most common way is to pass a python list

In [4]:
import numpy
array = numpy.array([1,2,3,4])
print(array)
print(array[1])

Solving environment: ...working... done

# All requested packages already installed.

[1 2 3 4]
2


* The biggest difference when compared to python lists is Num Py array need to be of the same type.

In [5]:
array = numpy.array([1,2,'a'])
print(array)

['1' '2' 'a']


* As shown in the above example if create numpy array with two numbers and one string, this causes Numpy to forcibly convert all elements in the array into strings

In [6]:
array
# U11 denotes the UniCode Strings with fewer than 11 Characters

array(['1', '2', 'a'], dtype='<U11')

In [8]:
array = numpy.array([1, 2.5])
array

array([1. , 2.5])

* We can create multi-dimensional Python lists, NumPy arrays support the same option:

In [9]:
matrices_np = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
matrices_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* We can create Numpy Arrays that are in a specific form
* If we want a matirx full of zeros or ones

In [11]:
zero_matrix = numpy.zeros((2,2))
print(zero_matrix)
zero_matrix

[[0. 0.]
 [0. 0.]]


array([[0., 0.],
       [0., 0.]])

In [12]:
one_matrix = numpy.ones((2,3,3))
print(one_matrix)
one_matrix

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
rand_matrix = numpy.random.rand(2,2)
print(rand_matrix)

[[0.55785567 0.23280566]
 [0.34730564 0.21514765]]
